In [1]:
import pandas as pd

In [2]:
Dataset = pd.read_csv(r"C:\Users\HP\Downloads\7. Udemy Courses.csv")

In [5]:
Dataset.head()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments

In [6]:
Dataset.tail()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20T22:15:17Z,Web Development
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26T20:04:21Z,Musical Instruments
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11T18:55:45Z,Web Development
3680,1225194,Zoho Books Gestion Financi√®re d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26T16:45:55Z,Business Finance
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

In [7]:
#What are the different subjects for which udemy is offering courses?

Dataset.subject.unique()

array(['Musical Instruments', 'Business Finance', 'Graphic Design',
       'Web Development'], dtype=object)

In [9]:
#What is the maximum number of courses for each subject

Dataset.subject.value_counts()

Web Development        1200
Business Finance       1199
Musical Instruments     680
Graphic Design          603
Name: subject, dtype: int64

In [11]:
#Show the all the free courses

Dataset[Dataset.is_paid==False]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
41,286070,5 lecciones que todo guitarrista debe tomar,False,Free,4452,263,14,Beginner Level,1 hour,2014-08-23T05:08:14Z,Musical Instruments
49,696630,"7 Ways A Beginner Guitarist Can Sound Better, ...",False,Free,4529,193,7,Beginner Level,36 mins,2015-12-21T18:50:50Z,Musical Instruments
57,955914,A beginner`s guide to fingerpicking and strumm...,False,Free,3481,29,20,Beginner Level,2 hours,2016-09-13T21:51:59Z,Musical Instruments
67,270976,A how to guide in HTML,False,Free,7318,205,8,Beginner Level,35 mins,2014-08-10T20:19:10Z,Web Development
74,1214144,¬°Triunfar en La Bolsa de Valores No Requiere d...,False,Free,338,7,6,Beginner Level,1 hour,2017-05-30T14:30:12Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3620,552598,WordPress in under an hour - Create/manage you...,False,Free,6474,86,15,All Levels,1 hour,2015-07-15T00:21:56Z,Web Development
3638,1068590,Wordpress Website Mastery 2017,False,Free,5181,64,22,Beginner Level,2.5 hours,2017-01-18T17:01:40Z,Web Development
3652,752706,Write quicker HTML5 and CSS 3; productivity ha...,False,Free,13016,286,15,All Levels,1.5 hours,2016-03-03T17:45:31Z,Web Development
3674,1257976,Your First 10 Guitar Lessons - Learn how to pl...,False,Free,924,4,18,Beginner Level,1 hour,2017-06-29T00:29:36Z,Musical Instruments
3680,1225194,Zoho Books Gestion Financi√®re d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26T16:45:55Z,Business Finance

In [16]:
#Show the all the paid courses

Dataset[Dataset.is_paid==True]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments
...,...,...,...,...,...,...,...,...,...,...,...
3676,498488,Your First Successful Forex Trades - With Case...,True,200,1079,34,16,All Levels,2.5 hours,2015-05-26T20:48:48Z,Business Finance
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20T22:15:17Z,Web Development
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26T20:04:21Z,Musical Instruments
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11T18:55:45Z,Web Development
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

In [18]:
# Which are the top selling courses

Dataset.sort_values('num_subscribers' , ascending = False)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
...,...,...,...,...,...,...,...,...,...,...,...
2290,1223240,Learn Pirates of the Caribbean by Ear on the P...,True,20,0,0,6,All Levels,32 mins,2017-05-22T17:14:43Z,Musical Instruments
1267,1258666,Financial Statement Auditing Cycles,True,50,0,0,9,Intermediate Level,2 hours,2017-06-29T23:20:10Z,Business Finance
2070,1215926,Kickstarter success in 5 easy steps,True,20,0,0,12,All Levels,31 mins,2017-05-16T14:55:28Z,Business Finance
1931,1247992,Introduction to Project Management for Finance...,True,50,0,0,9,Beginner Level,2 hours,2017-07-03T21:40:32Z,Business Finance
3165,1087466,Stop Creditors from Harassing you and Avoid Ba...,True,20,0,0,7,Beginner Level,37 mins,2017-02-02T16:22:37Z,Business Finance

In [19]:
# Which are the least selling courses

Dataset.sort_values('num_subscribers')

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
649,1233314,Building a Balanced Scorecard,True,50,0,0,11,Intermediate Level,2 hours,2017-07-03T21:38:22Z,Business Finance
3259,1232282,The Cash Flow Statement - An Introduction,True,50,0,0,10,Beginner Level,1.5 hours,2017-06-28T16:05:51Z,Business Finance
3261,1275872,The Complete Adobe Spark Course,True,150,0,0,29,All Levels,2 hours,2017-07-03T17:39:57Z,Graphic Design
910,726314,Create Beautiful Image Maps for Your Website,True,20,0,0,8,Intermediate Level,37 mins,2016-01-18T17:56:36Z,Graphic Design
3328,715476,The Cuckoo Strategy to get European Funding,True,160,0,0,6,All Levels,1 hour,2016-01-06T02:38:23Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development

In [28]:
#Show all course of Web Development/ Business Finance where the price is >= 100

Dataset[(Dataset.subject == "Web Development") & (Dataset.price >= "100")]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
11,64605,1 Hour CSS,True,100,18324,333,16,Beginner Level,1 hour,2013-07-09T20:27:14Z,Web Development
12,64422,1 Hour HTML,True,200,16212,514,20,Beginner Level,1 hour,2013-07-09T03:16:26Z,Web Development
13,63612,1 Hour JavaScript,True,200,22999,602,18,Beginner Level,1 hour,2013-07-04T15:27:02Z,Web Development
14,72262,1 hour jQuery,True,100,5456,133,25,Beginner Level,1 hour,2013-08-03T14:20:52Z,Web Development
24,975916,17 Complete JavaScript projects explained st...,True,185,327,26,106,Beginner Level,9.5 hours,2016-10-26T14:03:38Z,Web Development
...,...,...,...,...,...,...,...,...,...,...,...
3666,969170,XSD :basics for beginners,True,35,755,0,7,All Levels,42 mins,2016-09-27T18:01:26Z,Web Development
3667,968278,XSLT :basics for beginners,True,35,877,6,7,All Levels,32 mins,2016-09-27T15:14:59Z,Web Development
3670,560996,You can create Incredible Websites with HTML C...,True,100,11892,50,28,All Levels,2.5 hours,2015-09-12T01:35:41Z,Web Development
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20T22:15:17Z,Web Development
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11T18:55:45Z,Web Development

In [34]:
#show all courses List out all the courses that are related to Python

Dataset[Dataset.course_title.str.contains("Python")]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
216,599504,Advanced Scalable Python Web Development Using...,True,120,1299,56,71,Intermediate Level,14 hours,2016-08-11T22:09:24Z,Web Development
777,47963,"Coding for Entrepreneurs: Learn Python, Django...",True,195,23412,799,251,All Levels,45 hours,2013-04-08T00:46:14Z,Web Development
814,631128,Complete Python Web Course: Build 8 Python Web...,True,110,7489,941,173,All Levels,16 hours,2015-11-08T20:57:35Z,Web Development
842,186096,"Core: A Web App Reference Guide for Django, Py...",True,195,2497,98,154,All Levels,26 hours,2014-05-29T00:58:43Z,Web Development
1400,394832,Fun and creative web engineering with Python a...,False,Free,10917,319,25,All Levels,2 hours,2015-06-09T19:51:50Z,Web Development
1932,1038538,Introduction to QGIS Python Programming,True,85,197,26,28,Beginner Level,3.5 hours,2016-12-22T00:11:22Z,Web Development
1969,902888,Investment Portfolio Analysis with Python,True,50,209,13,37,All Levels,7 hours,2016-07-13T21:40:32Z,Business Finance
2294,391546,Learn Python and Django: Payment Processing,True,70,17714,198,23,All Levels,3.5 hours,2015-02-09T15:37:56Z,Web Development
2295,1063722,Learn Python Django - A Hands-On Course,True,50,1339,21,18,Beginner Level,2 hours,2017-01-18T21:53:34Z,Web Development
2341,546848,Learn to code in Python and learn Adobe Photos...,True,50,1132,1,29,All Levels,2 hours,2015-07-08T00:15:12Z,Graphic Design
2906,368340,Professional Python Web Development Using Flask,True,120,3420,489,102,Beginner Level,14.5 hours,2015-03-04T00:10:36Z,Web Development
2908,1035940,Professional RESTful API Design using Python F...,True,120,578,25,36,Intermediate Level,4.5 hours,2017-01-11T21:15:25Z,Web Development
2929,270808,Projects in Django and Python,True,60,1764,53,28,All Levels,6.5 hours,2014-10-21T07:58:07Z,Web Development
2952,1170894,Python Algo Stock Trading: Automate Your Trading!,True,95,1165,21,41,Beginner Level,2.5 hours,2017-05-28T23:41:03Z,Business Finance
2953,1070886,Python Algo Trading: FX Trading with Oanda,True,200,453,42,33,Intermediate Level,3 hours,2017-03-14T00:39:45Z,Business Finance
2954,1196544,Python Algo Trading: Sentiment Trading with News,True,200,294,19,42,All Levels,7 hours,2017-04-28T16:41:44Z,Business Finance
2955,822444,Python and Django Full Stack Web Developer Boo...,True,200,11832,1883,191,All Levels,31.5 hours,2017-02-24T18:40:55Z,Web Development
2956,477702,Python for Beginners: Python Programming Langu...,True,150,6153,125,84,Beginner Level,5 hours,2015-06-14T18:18:57Z,Web Development
2957,1035472,Python for Finance: Investment Fundamentals & ...,True,195,3811,278,103,All Levels,6.5 hours,2017-03-30T22:17:09Z,Business Finance
2958,529828,Python for Trading & Investing,True,95,638,25,36,All Levels,5 hours,2015-06-17T22:23:31Z,Business Finance
2959,70640,Python Programming: Create an Digital Marketpl...,True,195,4198,145,161,All Levels,26 hours,2013-10-20T19:53:28Z,Web Development
2960,523312,Python Web Programming,True,100,1020,46,60,Beginner Level,6 hours,2015-07-01T21:46:36Z,Web Development
2962,1088656,Quantitative Trading Analysis with Python,True,50,256,17,49,All Levels,5.5 hours,2017-01-27T17:11:28Z,Business Finance
3013,970600,REST APIs with Flask and Python,True,110,5151,737,115,Intermediate Level,12.5 hours,2016-11-06T19:00:38Z,Web Development
3154,815482,Stock Technical Analysis with Python,True,50,409,35,46,All Levels,8 hours,2016-04-12T00:40:03Z,Business Finance
3272,938560,The Complete Ethical Hacking Course 2.0: Pytho...,True,195,7827,268,66,All Levels,11 hours,2016-09-26T15:08:29Z,Web Development
3460,76052,Try Django 1.9 | Build a Blog and Learn Python...,True,50,7407,172,147,All Levels,20 hours,2014-03-04T07:12:21Z,Web Development
3573,16646,Web Programming with Python,True,50,35267,217,53,All Levels,4 hours,2012-04-25T00:01:43Z,Web Development
3574,574082,"Web Scraping with Python, Ruby & import. io",True,75,973,50,46,All Levels,4.5 hours,2015-08-09T22:16:41Z,Web Development

In [35]:
#show all courses List out all the courses that are related to SQL

Dataset[Dataset.course_title.str.contains("SQL")]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
56,304490,A 13 Hour SQL Server 2014 /ASP.NET/CSS/C#/jQue...,True,35,4183,231,86,Intermediate Level,14 hours,2014-10-12T06:29:05Z,Web Development
145,425084,Administering Microsoft SQL Server 2012 Databa...,True,60,586,65,98,All Levels,5.5 hours,2015-03-23T00:20:29Z,Web Development
273,1155262,Angular 2 Complete E-Commerce App Course - Jav...,True,195,949,129,89,All Levels,20.5 hours,2017-03-27T16:46:54Z,Web Development
585,992114,"Build A Complete CRUD Application With PHP, MY...",True,20,9762,94,112,All Levels,13.5 hours,2016-11-01T15:30:36Z,Web Development
653,155640,Building a Search Engine in PHP & MySQL,False,Free,10110,379,12,All Levels,2.5 hours,2014-02-03T18:07:52Z,Web Development
654,431576,Building a Social Network in PHP & MySQL From ...,True,50,869,125,78,All Levels,14 hours,2015-03-17T16:54:15Z,Web Development
799,1070976,"Complete E-Commerce Course - Java,Spring,Hiber...",True,195,1371,165,83,All Levels,20 hours,2017-01-16T23:50:02Z,Web Development
809,552198,Complete Login and Registration System in PHP ...,True,200,4714,149,28,All Levels,4 hours,2015-07-16T22:09:55Z,Web Development
821,98066,Complete Website & CMS in PHP & MySQL From Scr...,True,20,3357,82,48,All Levels,12.5 hours,2014-04-18T09:51:00Z,Web Development
892,418386,Create a REAL Social Network like Facebook in ...,True,45,1002,178,174,All Levels,16.5 hours,2016-09-19T15:54:37Z,Web Development
1305,921560,For Free - Deploy Quickly Spring Boot on Herok...,True,95,177,19,10,All Levels,1 hour,2016-08-06T07:33:17Z,Web Development
1789,425086,Implementing a Data Warehouse with SQL Server ...,True,85,1142,148,90,All Levels,5 hours,2015-05-01T23:08:38Z,Web Development
2165,267560,Learn E-Commerce Website in PHP & MySQL From S...,False,Free,29990,1342,87,All Levels,17.5 hours,2014-08-10T10:27:28Z,Web Development
2443,19603,Learning Dynamic Website Design - PHP MySQL an...,True,50,47886,285,125,All Levels,12.5 hours,2012-06-18T16:52:34Z,Web Development
2466,25615,Login and Registration from Scratch with PHP a...,True,20,1128,77,36,Intermediate Level,2 hours,2012-10-24T09:54:08Z,Web Development
2753,32649,PHP & MySQL - Learn The Easy Way. Master PHP &...,True,50,5549,92,143,All Levels,15.5 hours,2012-12-15T15:22:52Z,Web Development
2770,739770,PHP MySQL: Learn PHP MySQL with Project,True,20,2314,77,25,All Levels,2 hours,2016-04-21T02:06:22Z,Web Development
2781,519952,PHP: Complete Login and Registration System wi...,True,200,1448,173,48,All Levels,7.5 hours,2015-06-16T20:38:45Z,Web Development
2888,890810,Practical Understanding of PHP and MySQL,False,Free,12201,217,24,Beginner Level,5.5 hours,2016-07-06T16:35:25Z,Web Development
2937,266252,Projects in PHP and MySQL,True,60,10606,570,88,All Levels,23 hours,2014-07-25T11:11:41Z,Web Development
2964,422012,Querying Microsoft SQL Server 2012 - (Exam No....,True,85,666,89,115,All Levels,6.5 hours,2015-03-12T21:20:41Z,Web Development
3118,726290,Star Rating Project AJAX with JSON response fr...,True,120,1302,18,22,Beginner Level,1.5 hours,2016-01-13T17:02:38Z,Web Development
3304,1171966,The Complete PHP MySQL Professional Course wit...,True,200,16158,159,125,All Levels,19.5 hours,2017-06-07T05:58:36Z,Web Development
3388,978728,"Thoughtful Web Development Course: HTML, Vue.j...",True,200,842,144,536,All Levels,25 hours,2016-10-11T14:18:27Z,Web Development

In [36]:
#show all counts of courses that are related to Python

len(Dataset[Dataset.course_title.str.contains("Python")])

29

In [37]:
#show all counts of courses that are related to SQL

len(Dataset[Dataset.course_title.str.contains("SQL")])

24

In [42]:
Dataset.dtypes

course_id                            int64
course_title                        object
is_paid                               bool
price                               object
num_subscribers                      int64
num_reviews                          int64
num_lectures                         int64
level                               object
content_duration                    object
published_timestamp    datetime64[ns, UTC]
subject                             object
dtype: object

In [43]:
#What are courses published in the year 2015/2020/2023

#I had to change the datatype of 'published_timestamp'  from "object" to "datetime" before I can answer the above question.

Dataset["published_timestamp"] = pd.to_datetime(Dataset.published_timestamp)

In [48]:
Dataset['Year'] = Dataset['published_timestamp'].dt.year

In [49]:
Dataset

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Year
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18 05:07:05+00:00,Musical Instruments,2014
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12 19:06:34+00:00,Musical Instruments,2017
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26 18:34:57+00:00,Musical Instruments,2017
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21 23:48:18+00:00,Musical Instruments,2017
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21 23:44:49+00:00,Musical Instruments,2017
...,...,...,...,...,...,...,...,...,...,...,...,...
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20 22:15:17+00:00,Web Development,2015
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26 20:04:21+00:00,Musical Instruments,2015
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11 18:55:45+00:00,Web Development,2015
3680,1225194,Zoho Books Gestion Financi√®re d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26 16:45:55+00:00,Business Finance,2017
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26 22:19:48+00:00,Graphic Design,2016

In [50]:
Dataset['Month'] = Dataset['published_timestamp'].dt.month

In [51]:
Dataset

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Year,Month
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18 05:07:05+00:00,Musical Instruments,2014,9
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12 19:06:34+00:00,Musical Instruments,2017,4
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26 18:34:57+00:00,Musical Instruments,2017,4
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21 23:48:18+00:00,Musical Instruments,2017,2
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21 23:44:49+00:00,Musical Instruments,2017,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20 22:15:17+00:00,Web Development,2015,4
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26 20:04:21+00:00,Musical Instruments,2015,10
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11 18:55:45+00:00,Web Development,2015,11
3680,1225194,Zoho Books Gestion Financi√®re d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26 16:45:55+00:00,Business Finance,2017,5
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26 22:19:48+00:00,Graphic Design,2016,9

In [52]:
Dataset['Day'] = Dataset['published_timestamp'].dt.day

In [53]:
Dataset

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Year,Month,Day
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18 05:07:05+00:00,Musical Instruments,2014,9,18
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12 19:06:34+00:00,Musical Instruments,2017,4,12
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26 18:34:57+00:00,Musical Instruments,2017,4,26
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21 23:48:18+00:00,Musical Instruments,2017,2,21
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21 23:44:49+00:00,Musical Instruments,2017,2,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20 22:15:17+00:00,Web Development,2015,4,20
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26 20:04:21+00:00,Musical Instruments,2015,10,26
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11 18:55:45+00:00,Web Development,2015,11,11
3680,1225194,Zoho Books Gestion Financi√®re d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26 16:45:55+00:00,Business Finance,2017,5,26
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26 22:19:48+00:00,Graphic Design,2016,9,26

In [55]:
#What are courses published in the year 2014/2017/2020

Dataset[Dataset.Year == 2014]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Year,Month,Day
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18 05:07:05+00:00,Musical Instruments,2014,9,18
8,206592,:::Beginners Guide To Creating Amazing Images ...,True,25,72,5,17,Beginner Level,1 hour,2014-04-29 19:50:31+00:00,Graphic Design,2014,4,29
15,145220,1. Principles of Simple Interest,True,20,1074,6,13,All Levels,1 hour,2014-01-13 20:43:46+00:00,Business Finance,2014,1,13
17,157336,10. Bonds and Bond Pricing,True,20,308,4,10,All Levels,1 hour,2014-02-11 18:11:55+00:00,Business Finance,2014,2,11
21,315716,15 Mandamientos para ganar dinero en Bolsa,True,20,45,2,49,All Levels,8.5 hours,2014-10-14 17:33:27+00:00,Business Finance,2014,10,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3637,361620,Wordpress Tutorial,True,200,2311,8,44,All Levels,1.5 hours,2014-12-04 19:17:17+00:00,Web Development,2014,12,4
3643,326948,Working Capital Management for CA / CFA / CPA ...,True,25,2342,9,33,Intermediate Level,3.5 hours,2014-10-25 13:00:19+00:00,Business Finance,2014,10,25
3644,221872,Working Capital Management for Entrepreneurs,True,20,507,5,15,Expert Level,1 hour,2014-11-19 10:36:51+00:00,Business Finance,2014,11,19
3669,180384,Yield Curve Dynamics,True,50,397,24,19,All Levels,3 hours,2014-03-12 14:54:48+00:00,Business Finance,2014,3,12
3671,144222,"YOU can Draw, Shade and Paint a Mixed Media Gi...",True,30,1249,44,19,Beginner Level,3 hours,2014-01-28 02:30:26+00:00,Graphic Design,2014,1,28

In [56]:
#What are courses published in the year 2014/2017/2020

Dataset[Dataset.Year == 2017]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Year,Month,Day
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12 19:06:34+00:00,Musical Instruments,2017,4,12
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26 18:34:57+00:00,Musical Instruments,2017,4,26
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21 23:48:18+00:00,Musical Instruments,2017,2,21
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21 23:44:49+00:00,Musical Instruments,2017,2,21
5,1122832,#6 Piano Hand Coordination: Play Open 10 Balla...,True,65,2015,3,21,Intermediate Level,44 mins,2017-03-08 17:53:36+00:00,Musical Instruments,2017,3,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3662,1115132,XML XQuery - Crash Course for Beginners,True,45,426,4,10,All Levels,1 hour,2017-02-19 22:52:36+00:00,Web Development,2017,2,19
3663,1115126,XML XSLT - Crash Course for Beginners,True,45,426,4,9,All Levels,1 hour,2017-02-19 18:11:07+00:00,Web Development,2017,2,19
3672,1031698,You Can Play Jazz Saxophone,True,20,37,7,6,Beginner Level,1.5 hours,2017-03-15 16:20:15+00:00,Musical Instruments,2017,3,15
3674,1257976,Your First 10 Guitar Lessons - Learn how to pl...,False,Free,924,4,18,Beginner Level,1 hour,2017-06-29 00:29:36+00:00,Musical Instruments,2017,6,29
3680,1225194,Zoho Books Gestion Financi√®re d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26 16:45:55+00:00,Business Finance,2017,5,26

In [60]:
#What are courses published in the year 2014/2017/2020

Dataset[Dataset.Year == 2020]

Empty DataFrame
Columns: [course_id, course_title, is_paid, price, num_subscribers, num_reviews, num_lectures, level, content_duration, published_timestamp, subject, Year, Month, Day]
Index: []

In [63]:
#What are courses published in the month of March 2014/2017/2020

Dataset[Dataset.Month == 3]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Year,Month,Day
5,1122832,#6 Piano Hand Coordination: Play Open 10 Balla...,True,65,2015,3,21,Intermediate Level,44 mins,2017-03-08 17:53:36+00:00,Musical Instruments,2017,3,8
6,1123184,#7 Piano Hand Coordination: Play Piano Runs in...,True,65,2015,2,25,Intermediate Level,1 hour,2017-03-08 18:09:32+00:00,Musical Instruments,2017,3,8
7,768028,* An Integrated Approach to the Fundamentals o...,True,200,134,14,123,All Levels,5.5 hours,2016-03-15 17:23:07+00:00,Business Finance,2016,3,15
16,302450,10 Numbers Every Business Owner Should Know,True,20,13,1,9,All Levels,1 hour,2015-03-08 19:11:24+00:00,Business Finance,2015,3,8
50,665042,8 Beautiful Ruby on Rails Apps in 30 Days & TD...,True,100,5962,466,132,All Levels,16 hours,2016-03-08 07:36:40+00:00,Web Development,2016,3,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3639,1122306,Wordpress: Comment utiliser le th√®me FABLE,True,20,1,0,10,Beginner Level,39 mins,2017-03-07 16:53:27+00:00,Graphic Design,2017,3,7
3652,752706,Write quicker HTML5 and CSS 3; productivity ha...,False,Free,13016,286,15,All Levels,1.5 hours,2016-03-03 17:45:31+00:00,Web Development,2016,3,3
3654,440006,X theme for WordPress: Responsive web design w...,True,20,1318,81,55,All Levels,7 hours,2015-03-22 22:46:36+00:00,Web Development,2015,3,22
3669,180384,Yield Curve Dynamics,True,50,397,24,19,All Levels,3 hours,2014-03-12 14:54:48+00:00,Business Finance,2014,3,12
3672,1031698,You Can Play Jazz Saxophone,True,20,37,7,6,Beginner Level,1.5 hours,2017-03-15 16:20:15+00:00,Musical Instruments,2017,3,15

In [65]:
len(Dataset[Dataset.Month == 3])

364

In [68]:
Dataset.sort_values('Month' , ascending = False)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Year,Month,Day
205,368958,Advanced Graphic Design-Photoshop CC 2014 for ...,True,20,314,11,19,All Levels,1.5 hours,2014-12-19 05:55:57+00:00,Graphic Design,2014,12,19
3100,379814,"Sketching: How to Draw People, Hands, Eyes, Bu...",True,20,500,16,31,All Levels,2 hours,2014-12-29 21:50:46+00:00,Graphic Design,2014,12,29
1980,1025026,Javascript - From Beginner to Pro-Build real w...,True,195,28694,688,77,Beginner Level,11.5 hours,2016-12-11 21:16:42+00:00,Web Development,2016,12,11
3071,1033944,Serverless Workflow Management with AWS Step F...,False,Free,8768,173,8,Intermediate Level,1 hour,2016-12-09 03:39:22+00:00,Web Development,2016,12,9
1964,572992,Investing: How to Fix Hidden Flaws Inside Your...,True,195,58,8,14,All Levels,1 hour,2015-12-03 02:30:13+00:00,Business Finance,2015,12,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092,1079040,Leaps Options Trading System - Diagonal Leaps ...,True,200,993,19,16,All Levels,1 hour,2017-01-19 19:09:29+00:00,Business Finance,2017,1,19
181,1080584,Adobe Photoshop CC for Photographers Advanced,True,30,1,0,43,Expert Level,2.5 hours,2017-01-19 22:12:04+00:00,Graphic Design,2017,1,19
3263,380970,The Complete Bitcoin Course: Get .001 Bitcoin ...,True,45,8797,449,80,All Levels,6.5 hours,2015-01-09 03:55:15+00:00,Business Finance,2015,1,9
1965,382824,Investment Banking Operations : Securities Tra...,True,30,267,9,10,All Levels,2 hours,2015-01-02 10:18:52+00:00,Business Finance,2015,1,2
2046,379722,jQuery Crash Course: Learn the Essentials of j...,True,50,11262,142,18,All Levels,2 hours,2015-01-07 03:12:34+00:00,Web Development,2015,1,7

In [74]:
#Month with highest publication

Dataset.value_counts('Month')

Month
5     376
3     364
4     357
6     353
2     339
11    298
1     293
10    286
7     278
8     254
12    245
9     239
dtype: int64

In [75]:
#Days with highest publication

Dataset.value_counts('Day')

Day
29    150
13    147
12    141
19    135
23    132
1     132
17    131
27    129
3     129
24    128
8     127
28    126
22    125
2     122
18    122
9     121
26    118
6     117
21    116
16    115
20    112
14    112
7     111
10    110
15    108
11    107
25    106
5     102
4     101
30     95
31     55
dtype: int64

In [76]:
#Year with highest publication

Dataset.value_counts('Year')

Year
2016    1206
2015    1014
2017     719
2014     491
2013     202
2012      45
2011       5
dtype: int64

In [81]:
#What are the max nmber of subscribers for each level of courses.

Dataset.groupby('level')['num_subscribers'].max()

level
All Levels            268923
Beginner Level        161029
Expert Level            5172
Intermediate Level     29167
Name: num_subscribers, dtype: int64

In [82]:
Dataset.groupby('level').max()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,content_duration,published_timestamp,subject,Year,Month,Day
level,,,,,,,,,,,,,
All Levels,1277924,ÔºñÊôÇÈñì„Åß„Ç§„É≥„Çø„Éº„Éê„É≥„ÇØÂ∏ÇÂ†¥„ÇíÊîªÁï•ÔºÅÊúÄÁü≠Ë∑ùÈõ¢„Åß„Éà„É¨„Éº„ÉâÂü∫Á§éÂäõ,True,Free,268923,27445,544,9.5 hours,2017-07-06 21:16:13+00:00,Web Development,2017,12,31
Beginner Level,1282064,ÔºóÊó•„Åß„Éû„Çπ„Çø„Éº „Éì„ÇÆ„Éä„ÉºÂêë„Åë Adobe Illustrator„ÄÄ„Å©„Åç„Å©„Åç„Çª„Éü„Éä„Éº,True,Free,161029,5924,779,9.5 hours,2017-07-06 21:46:30+00:00,Web Development,2017,12,31
Expert Level,1275790,[Value Investing] Where White People Keep Thei...,True,95,5172,249,157,9 hours,2017-07-04 18:08:01+00:00,Web Development,2017,12,30
Intermediate Level,1276182,Ê†™ÂºèÊäïË≥á„ÅßÊú¨ÂΩì„ÅÆ„ÉÜ„ÇØ„Éã„Ç´„É´ÂàÜÊûê„Åå„Åß„Åç„Çã„Çà„ÅÜ„Å´„Å™„Çã,True,Free,29167,3326,320,9.5 hours,2017-07-05 04:41:54+00:00,Web Development,2017,12,31

In [85]:
Dataset.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3677    False
3678    False
3679    False
3680    False
3681    False
Length: 3682, dtype: bool